# VaultDynamicSecret 예제
# Vault가 동적으로 생성하는 Database 자격 증명을 Kubernetes Secret으로 동기화합니다.
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: myapp-db-creds
  namespace: default
spec:
  # 사용할 VaultAuth
  vaultAuthRef: default
  
  # Database Secret Engine 경로
  mount: database
  path: creds/readwrite
  
  # 생성할 Kubernetes Secret
  destination:
    name: myapp-db-dynamic
    create: true
    labels:
      app: myapp
      managed-by: vault
  
  # Lease 설정
  renewalPercent: 67  # TTL의 67%가 지나면 갱신
  revoke: true        # CR 삭제 시 Vault에서 Lease 폐기
  
  # Secret 갱신 시 자동으로 재시작할 리소스
  rolloutRestartTargets:
    - kind: Deployment
      name: myapp
---
# 애플리케이션 Deployment
# Dynamic Secret을 사용하는 애플리케이션
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: myapp-sa
      containers:
      - name: app
        image: postgres:15-alpine
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: myapp-db-dynamic
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-db-dynamic
              key: password
        - name: DB_HOST
          value: postgres.default.svc.cluster.local
        - name: DB_NAME
          value: myappdb
        command:
        - sh
        - -c
        - |
          echo "Connecting to database with dynamic credentials..."
          echo "Username: $DB_USERNAME"
          
          # 60초마다 데이터베이스 버전 확인
          while true; do
            echo "$(date): Querying database..."
            psql "postgresql://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:5432/$DB_NAME" \
              -c "SELECT current_user, version();" || echo "Connection failed"
            sleep 60
          done
