# VaultStaticSecret 예제
# Vault의 KV Secret을 Kubernetes Secret으로 동기화합니다.
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: myapp-database-secret
  namespace: default
spec:
  # 사용할 VaultAuth
  vaultAuthRef: default
  
  # Vault Secret 경로
  mount: secret
  type: kv-v2
  path: myapp/database
  
  # 생성할 Kubernetes Secret
  destination:
    name: myapp-database
    create: true
    # labels:
    #   app: myapp
    # annotations:
    #   description: "Database credentials"
  
  # 갱신 간격 (초 단위)
  refreshAfter: 30s
  
  # Secret 데이터 HMAC (기본값: true)
  # hmacSecretData: true
---
# ServiceAccount
# VSO가 이 ServiceAccount를 사용하여 Vault에 인증합니다.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: default
---
# 테스트 Pod
# 생성된 Kubernetes Secret을 사용하는 예제 Pod
apiVersion: v1
kind: Pod
metadata:
  name: myapp-test
  namespace: default
spec:
  serviceAccountName: myapp-sa
  containers:
  - name: app
    image: nginx:latest
    env:
    # 환경 변수로 Secret 사용
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: myapp-database
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: myapp-database
          key: password
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: myapp-database
          key: host
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: myapp-database
          key: port
    # 또는 볼륨으로 마운트
    volumeMounts:
    - name: db-creds
      mountPath: /etc/secrets
      readOnly: true
    command:
    - sh
    - -c
    - |
      echo "Database credentials loaded:"
      echo "Host: $DB_HOST:$DB_PORT"
      echo "User: $DB_USERNAME"
      echo "Files in /etc/secrets:"
      ls -la /etc/secrets/
      tail -f /dev/null
  volumes:
  - name: db-creds
    secret:
      secretName: myapp-database
