# PostgreSQL Dynamic Secrets 전체 예제
# 이 파일에는 PostgreSQL 배포부터 Dynamic Secrets 사용까지 모든 리소스가 포함되어 있습니다.

---
# ConfigMap: PostgreSQL 초기화 스크립트
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: default
data:
  init.sql: |
    -- Vault가 사용할 관리자 계정 생성
    CREATE USER vaultadmin WITH PASSWORD 'vaultpassword' SUPERUSER;
    
    -- 애플리케이션 데이터베이스 준비
    CREATE TABLE IF NOT EXISTS app_data (
      id SERIAL PRIMARY KEY,
      data TEXT,
      created_at TIMESTAMP DEFAULT NOW()
    );
    
    INSERT INTO app_data (data) VALUES ('Sample data 1'), ('Sample data 2');

---
# Deployment: PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: myappdb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: rootpassword
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: init-script
        configMap:
          name: postgres-init
      - name: postgres-data
        emptyDir: {}

---
# Service: PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  type: ClusterIP

---
# VaultConnection
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
  namespace: default
spec:
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true

---
# VaultAuth
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: default
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: myapp-role
    serviceAccount: myapp-sa

---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: default

---
# VaultDynamicSecret
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: postgres-db-creds
  namespace: default
spec:
  vaultAuthRef: default
  mount: database
  path: creds/readwrite
  destination:
    name: postgres-db-creds
    create: true
  renewalPercent: 67
  revoke: true
  rolloutRestartTargets:
    - kind: Deployment
      name: postgres-app

---
# Deployment: 애플리케이션
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      serviceAccountName: myapp-sa
      containers:
      - name: app
        image: postgres:15-alpine
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-db-creds
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db-creds
              key: password
        - name: PGHOST
          value: postgres
        - name: PGDATABASE
          value: myappdb
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-db-creds
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db-creds
              key: password
        command:
        - sh
        - -c
        - |
          echo "=== PostgreSQL Dynamic Secrets Demo ==="
          echo "Starting application..."
          
          while true; do
            echo ""
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Querying database..."
            echo "Current user: $DB_USERNAME"
            
            # 현재 사용자 확인
            psql -c "SELECT current_user, current_timestamp;"
            
            # 데이터 조회
            psql -c "SELECT * FROM app_data LIMIT 5;"
            
            # 연결 정보
            psql -c "SELECT 
              usename AS username,
              application_name,
              client_addr,
              state,
              query_start
            FROM pg_stat_activity 
            WHERE usename = current_user;"
            
            echo "Sleeping for 30 seconds..."
            sleep 30
          done
