dex:
  enabled: false

global:
  nodeSelector:
    app: argocd

configs:
  cm:
    server.insecure: true

  params:
    server.insecure: true

server:
  service:
    type: ClusterIP

  insecure: true
  ingress:
    enabled: false
